POST http://localhost:4001/api/login
Content-Type: application/json

# {
#     "username": "mikkaiekusd",
#     "name": "mikkaeiku Akkurdibe",
#     "password": "AscashuFalas"
# }

{
    "username": "Elixhir",
    "name": "Aejhin ahbitl",
    "password": "Creopaxta1"
}